- name: Deploy Kasten on Microshift
  hosts: personal-k8s
  remote_user: ansible
  become: yes

  tasks:
  - name: Copy over deployment yamls from ./applications/*
    copy:
      src: ./applications/
      dest: /tmp/deployments/

  - name: Install Git
    dnf:
      name: git
      state: present

  - name: Apply Volumesnapshotclass Deployment
    shell: kubectl apply -f /tmp/deployments/kasten/volumesnapshotclass.yaml

  - name: Install helm.
    shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    ignore_errors: yes

  - name: Check if /usr/local/bin is in $PATH.
    shell: echo $PATH | grep -q /usr/local/bin
    register: path_check

  - name: Add /usr/local/bin to PATH
    shell: export PATH=$PATH:/usr/local/bin
    when: path_check.rc != 0

  - name: Add Kasten Helm Repo
    shell: helm repo add kasten https://charts.kasten.io/

  - name: Run K10 primer script.
    shell: curl -s https://docs.kasten.io/tools/k10_primer.sh | bash /dev/stdin csi -s topolvm-provisioner
    register: k10_primer

  - name: Check for Successfully tested snapshot restore functionality. - OK in output of k10_primer.
    debug:
      msg: "{{ k10_primer.stdout }}"
  
