### Threw this together based off of documentation provided by Kasten for the configuration of Microshift and Application level backups on RHEL9.
### You will need to go to the Red Hat Hybrid Cloud Console and get an Openshift Pull Secret https://console.redhat.com/openshift/create/local
### I have a basic ansible user configured with passwordless access as a service account on my K9S server that I will use to run this playbook.
### My host configuration matches their recommendation. I have RHEL9 installed on a 40GB partition located at /dev/sda and a second 100GB partition located at /dev/sdb.
### You can run this on baremetal, or on any hypervisor platform. I use Proxmox at home, just double check the drive mappings before running the playbook and you are good to go.

- name: Deploy Microshift and configure other applications and services on RHEL 9.
  hosts: personal-k8s
  remote_user: ansible
  become: yes

  vars_prompt:
    - name: OpenshiftAPIKey
      prompt: "Enter your OpenShift API Key"
      private: yes  

  tasks: 

### First rule of installations, update and ugpgrade!
  - name: Update DNF and Ugrade.
    dnf:
      name: '*'
      state: latest
      update_cache: yes

  - name: Check to see if PV is already created.
    shell: pvdisplay | grep /dev/sdb
    register: pv_check

  - name: Create PV on new partition.
    shell: pvcreate /dev/sdb
    when: pv_check.rc != 0

  - name: Create VG for Microshift
    shell: vgcreate microshift-vg /dev/sdb
    when: pv_check.rc != 0

  - name: Create LV for Microshift
    shell: lvcreate -L 80G -T microshift-vg/microshift-lv
    when: pv_check.rc != 0

  - name: Put Openshift API key in to /etc/crio/openshift-pull-secret
    shell: 'echo "{{ OpenshiftAPIKey }}" > /etc/crio/openshift-pull-secret'

  - name: Set permissions on /etc/crio/openshift-pull-secret
    shell: chmod 600 /etc/crio/openshift-pull-secret

  - name: Configure Firewalld for Microshift.
    shell: firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 && firewall-cmd --permanent --zone=trusted --add-source=169.254.169.1 && firewall-cmd --reload

  - name: Start and enable Microshift
    shell: systemctl enable --now microshift

  - name: Configure the device class within LVMS to use the thin logical volume.
    lineinfile:
      path: /etc/microshift/lvmd.yaml
      line: |-
        device-classes:
        - name: default
          default: true
          spare-gb: 0
          thin-pool:
            name: mythinpool
            overprovision-ratio: 10
            type: thin
            volume-group: microshift-vg

  - name: Copy kubeconfig from /var/lib/microshift/resources/kubeadmin/kubeconfig to ~/.kube/config
    shell: cp /var/lib/microshift/resources/kubeadmin/kubeconfig ~/.kube/config

  - name: Set permissions on ~/.kube/config
    shell: chmod go-r ~/.kube/config

  - name: Restart Microshift
    shell: systemctl restart microshift

