apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letsencrypt-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-12-19T21:51:05Z"
  labels:
    app: nginx-proxy-pod
  name: nginx-proxy-pod
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: docker.io/jc21/nginx-proxy-manager:latest
    name: nginx-proxy
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 256Mi
        cpu: 250m
    ports:
    - containerPort: 80
      hostPort: 30080
    - containerPort: 81
      hostPort: 30081
    - containerPort: 443
      hostPort: 30443
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /data
      name: data-pvc
    - mountPath: /etc/letsencrypt
      name: letsencrypt-pvc
  volumes:
  - name: data-pvc
    persistentVolumeClaim:
      claimName: data-pvc
  - name: letsencrypt-pvc
    persistentVolumeClaim:
      claimName: letsencrypt-pvc